### ISSUE TITLE
Declaration of Conso\Commands\Info::execute must be compatible with Conso\Contarcts\CommandInterface::execute

### ISSUE THREAD

**Issue by NesCafe62** [lotfio/conso#5]
There is a Fatal Error when I try to run `php conso`. Tried this with php 7.2.

**Comment by lotfio** [comment]
Sounds like you have created a new command which does not respect ComandInterface ! could you please provide more information about what you have done so far so i can figure out what happend.
conso works fine with PHP 7.2  after installing the package you can just run `./vendor/bin/conso` and it will work fine Thanks :)

**Comment by NesCafe62** [comment]
sorry it is for php 7.1, I forgot to change system PATH and restart, with 7.2 it is ok. You can close thie issue.
